### ISSUE TITLE
Bootstrap not loading on https

### ISSUE THREAD

**Issue by Kiailandi** [agajews/apricity-site#2]
Bootstrap js and css are requested via http, if https is enabled the requests are blocked and style results broken. [tested on chrome]

Screenshot of the error (chrome console):
![image](https://cloud.githubusercontent.com/assets/1914074/14409379/afb89dca-ff11-11e5-80ee-7b67b2da41b5.png)

EDIT: seems fixed on repo, but not on live.

**Comment by ghost** [comment]
![schermata 2016-04-10 alle 12 49 02](https://cloud.githubusercontent.com/assets/18188458/14409677/9c01a11a-ff1a-11e5-8488-01790185395d.png)
Temporary solution

**Comment by agajews** [comment]
Fixed. Thanks.
